### PR TITLE
New install method

### PR DESCRIPTION
**Pull request by marina-manrique**
I don't like installing Velvet cloning the git repo as I don't know the Velvet version we are installing and it seems to me the repo does not have the current version of the tool 

I'm changing this

### CODE REVIEW

**Comment by laughedelic** [comment]
this is wise :+1: 
but what are you going to do instead?

**Comment by marina-manrique** [comment]
I've downloaded the current version from the _oficial_ website https://www.ebi.ac.uk/~zerbino/velvet/ and I have uploaded the `tar.gz` file to S3 as we normally do

**Comment by laughedelic** [comment]
:shipit: :ok_hand:

**Comment by marina-manrique** [comment]
@laughedelic in the end I managed to get it working without the `@@` operators, should I merge the pull request?

**Comment by laughedelic** [comment]
Sure :+1: 
I only think that you forgot to remove the ammonite dependency (I guess it's not used anymore)

**Comment by marina-manrique** [comment]
Ok, I'm doing it

**Pull request merged**
